baseURL: "https://pfalcao97.githubpages.io/blog"
theme: "PaperMod"

enableEmoji: true

params:
  ShowCodeCopyButtons: true
  math: true

  homeInfoParams:
    Title: "Olá!"
    Content: "Textos sobre Programação, Ciência e Matemática!"

  socialIcons:
    - name: github
      url: "https://github.com/Pfalcao97"
    - name: linkedin
      url: "https://www.linkedin.com/in/pfalcao97"

  ShowBreadCrumbs: true
  ShowReadingTime: true
  ShowShareButtons: true

outputs:
  home:
    - HTML
    - RSS
    - JSON

# Language configuration

DefaultContentLanguage: pt
defaultContentLanguageInSubdir: false

languages:
  pt:
    languageName: "Português :brazil:"
    title: "Blog de Pedro Falcão"

    menu:
      main:
        - identifier: categories
          name: "Categorias"
          url: "/categories/"
          weight: 10
        - identifier: aboutme
          name: "Sobre mim"
          url: "/aboutme/"
          weight: 20
        - identifier: archives
          name: Blog Posts
          url: /archives/
          weight: 30


taxonomies:
  category: categories
  tag: tags
